Repository Libvisual/libvisual, pull requests merged in 2023-02, with the labels that each got.

#229 [0.4.x] libvisual + libvisual-plugins: Re-write autogen.sh based on autoreconf
  .github/workflows/linux_and_macos.yml
  .github/workflows/translations.yml
  libvisual-plugins/autogen.sh
  libvisual/autogen.sh
Labels: enhancement, porting: not needed

#236 [0.4.x] libvisual-plugins: Improve error handling in .init of input plugin "portaudio"
  libvisual-plugins/plugins/input/portaudio/input_portaudio.c
Labels: enhancement, porting: done

#233 [0.4.x] lv-tool: Rename binary from "lv-tool" to "lv-tool-0.4"
  libvisual/configure.ac
  libvisual/tools/lv-tool/Makefile.am
Labels: enhancement, porting: TODO

#235 Fix CI regarding installation of Clang 16 + start covering Clang 17
  .github/workflows/linux.yml
  libvisual/tools/lv-tool/display/sdl_driver.cpp
  libvisual/tools/lv-tool/display/stdout_sdl_driver.cpp
Labels: enhancement, porting: done

#239 [0.4.x] lv-tool: Increase initial/default resolution from 320x200 to 640x480
  libvisual/tools/lv-tool/lv-tool.cpp
Labels: enhancement, porting: TODO

#240 [0.4.x] libvisual-plugins: Fix flipped assertion in .init of input "portaudio"
  libvisual-plugins/plugins/input/portaudio/input_portaudio.c
Labels: bug, critical, porting: not needed

#242 lv-tool: Rename binary from "lv-tool" to "lv-tool-0.5"
  libvisual/tools/lv-tool/CMakeLists.txt
Labels: enhancement, porting: done

#241 libvisual-plugins: Migrate PulseAudio input plugin to PulseAudio's Asynchronous API (fixes #33)
  libvisual-plugins/CMakeLists.txt
  libvisual-plugins/plugins/input/pulseaudio/input_pulseaudio.c
Labels: bug, critical, porting: done

#243 lv-tool: Increase initial resolution from 320x200 to 640x480
  libvisual/tools/lv-tool/lv-tool.cpp
Labels: enhancement, porting: done

#238 [0.4.x] libvisual: Stop using sdl-config and AM_PATH_SDL in configure.ac
  libvisual/configure.ac
Labels: enhancement, porting: not needed

#234 libvisual-plugins: Add PortAudio input plugin (e.g. for macOS, non-blocking I/O)
  .github/workflows/linux.yml
  .github/workflows/windows.yml
  libvisual-plugins/CMakeLists.txt
  libvisual-plugins/plugins/input/CMakeLists.txt
  libvisual-plugins/plugins/input/portaudio/CMakeLists.txt
  libvisual-plugins/plugins/input/portaudio/input_portaudio.c
  libvisual-plugins/po/POTFILES.in
Labels: enhancement, porting: done

#251 Core (Build): Fix include directories for 'libvisual' target.
  libvisual/cmake/LVBuildTest.cmake
  libvisual/examples/CMakeLists.txt
  libvisual/examples/simple/simple_example.hpp
  libvisual/libvisual/CMakeLists.txt
  libvisual/tools/benchmarks/CMakeLists.txt
  libvisual/tools/lv-tool/CMakeLists.txt
Labels: enhancement

#248 Plugins (pulseaudio): Use C11 atomics in place of GCC/Clang extensions.
  libvisual-plugins/plugins/input/pulseaudio/input_pulseaudio.c
Labels: enhancement

#253 [0.4.x] libvisual-plugins: Remove actor plugin "finespectrum" (related to #207)
  libvisual-plugins/plugins/actor/finespectrum/Makefile.am
  libvisual-plugins/plugins/actor/finespectrum/actor_finespectrum.c
Labels: enhancement, porting: done

#256 lv-tool: Demote actor "lv_analyzer" (related to #207)
  libvisual/tools/lv-tool/lv-tool.cpp
Labels: enhancement, porting: done

#259 Core (LV::Video): Fix incorrect pointer increments in ARGB32 video byte swaps
  libvisual/libvisual/private/lv_video_convert.cpp
Labels: bug, critical

#252 Core (Memory): Streamline AlignedAllocator for C++17
  libvisual/libvisual/lv_aligned_allocator.hpp
  libvisual/tests/CMakeLists.txt
  libvisual/tests/mem_test/CMakeLists.txt
  libvisual/tests/mem_test/aligned_allocation_test.cpp
Labels: enhancement

#268 [0.4.x] libvisual: Improve AltiVec detection for PPC/PPC64 Linux
  libvisual/libvisual/lv_cpu.c
Labels: bug, porting: TODO

#257 lv-tool: Debounce resize requests (fixes #161)
  libvisual/tools/lv-tool/display/sdl_driver.cpp
  libvisual/tools/lv-tool/display/stdout_sdl_driver.cpp
  libvisual/tools/lv-tool/lv-tool.cpp
Labels: bug, porting: done

#270 Core (lv-tool): Apply 'override' and 'final' to classes.
  libvisual/tools/lv-tool/display/display.hpp
  libvisual/tools/lv-tool/display/display_driver_factory.hpp
  libvisual/tools/lv-tool/display/sdl_driver.cpp
  libvisual/tools/lv-tool/display/stdout_driver.cpp
  libvisual/tools/lv-tool/display/stdout_sdl_driver.cpp
  libvisual/tools/lv-tool/lv-tool.cpp
Labels: enhancement

#265 Core: Add LV_NODISCARD for C API functions with non-discardable results
  libvisual/libvisual/lv_actor.h
  libvisual/libvisual/lv_audio.h
  libvisual/libvisual/lv_bin.h
  libvisual/libvisual/lv_buffer.h
  libvisual/libvisual/lv_color.h
  libvisual/libvisual/lv_defines.h
  libvisual/libvisual/lv_event.h
  libvisual/libvisual/lv_fourier.h
  libvisual/libvisual/lv_input.h
  libvisual/libvisual/lv_mem.h
  libvisual/libvisual/lv_morph.h
  libvisual/libvisual/lv_palette.h
  libvisual/libvisual/lv_param.h
  libvisual/libvisual/lv_param_validators.h
  libvisual/libvisual/lv_param_value.h
  libvisual/libvisual/lv_random.h
  libvisual/libvisual/lv_rectangle.h
  libvisual/libvisual/lv_songinfo.h
  libvisual/libvisual/lv_time.h
  libvisual/libvisual/lv_util.h
  libvisual/libvisual/lv_video.h
Labels: enhancement

#274 Core: Fix LV_RESTRICT not correctly defined in C++ when compiling with GCC and Clang.
  libvisual/libvisual/lv_defines.h
Labels: bug, critical

#281 [0.4.x] libvisual-plugins: Fix allocation size in "corona" to fix heap-buffer-overflow (fixes #263)
  libvisual-plugins/plugins/actor/corona/corona.cpp
Labels: bug

#289 libvisual-plugins: Fix allocation size in "corona" to fix heap-buffer-overflow (fixes #263)
  libvisual-plugins/plugins/actor/corona/corona.cpp
Labels: bug, porting: done

#290 [0.4.x] libvisual-plugins: Fix compile error for actor "gforce" (e.g. for macOS)
  libvisual-plugins/plugins/actor/G-Force/GForceCommon/G-Force.cpp
  libvisual-plugins/plugins/actor/G-Force/GForceCommon/Headers/G-Force.h
Labels: bug, porting: TODO

#284 Core (Memory): Remove custom implementations of memset() and memcpy().
  libvisual/libvisual/lv_mem.c
Labels: clean up

#282 Core: Enhance and clean up singleton classes
  libvisual/libvisual/lv_libvisual.cpp
  libvisual/libvisual/lv_libvisual.h
  libvisual/libvisual/lv_plugin_registry.cpp
  libvisual/libvisual/lv_plugin_registry.h
  libvisual/libvisual/lv_singleton.hpp
Labels: enhancement
