Repository Libvisual/libvisual, pull requests merged in 2023-03, with the labels that each got.

#262 [0.4.x] libvisual + libvisual-plugins: Cover more compilers for macOS
  .github/workflows/linux_and_macos.yml
Labels: bug, porting: TODO

#280 Core: Use C++ concepts to improve template errors and simplify TMP
  libvisual/libvisual/lv_intrusive_ptr.hpp
  libvisual/libvisual/private/lv_audio_convert.cpp
Labels: enhancement

#285 Core (Memory): Re-implement visual_mem_set{16,32} to exploit GCC/Clang auto-vectorisation
  libvisual/libvisual/lv_mem.c
  libvisual/tests/mem_test/CMakeLists.txt
  libvisual/tests/mem_test/mem_set_test.cpp
Labels: enhancement

#272 Core: Optimize string arguments and returns
  libvisual/libvisual/lv_actor.cpp
  libvisual/libvisual/lv_actor.h
  libvisual/libvisual/lv_audio.cpp
  libvisual/libvisual/lv_audio.h
  libvisual/libvisual/lv_bin.cpp
  libvisual/libvisual/lv_bin.h
  libvisual/libvisual/lv_input.cpp
  libvisual/libvisual/lv_input.h
  libvisual/libvisual/lv_libvisual.cpp
  libvisual/libvisual/lv_libvisual.h
  libvisual/libvisual/lv_libvisual_c.cpp
  libvisual/libvisual/lv_morph.cpp
  libvisual/libvisual/lv_morph.h
  libvisual/libvisual/lv_param.cpp
  libvisual/libvisual/lv_param.h
  libvisual/libvisual/lv_plugin_registry.cpp
  libvisual/libvisual/lv_plugin_registry.h
  libvisual/libvisual/lv_songinfo.cpp
  libvisual/libvisual/lv_songinfo.h
  libvisual/libvisual/private/lv_string_hash.hpp
  libvisual/tools/benchmarks/actor_bench.cpp
  libvisual/tools/benchmarks/benchmark.hpp
  libvisual/tools/benchmarks/morph_bench.cpp
  libvisual/tools/lv-tool/display/display.cpp
  libvisual/tools/lv-tool/display/display.hpp
  libvisual/tools/lv-tool/display/display_driver.hpp
  libvisual/tools/lv-tool/display/display_driver_factory.cpp
  libvisual/tools/lv-tool/display/display_driver_factory.hpp
  libvisual/tools/lv-tool/display/sdl_driver.cpp
  libvisual/tools/lv-tool/display/stdout_driver.cpp
  libvisual/tools/lv-tool/display/stdout_sdl_driver.cpp
  libvisual/tools/lv-tool/lv-tool.cpp
Labels: enhancement

#298 [0.4.x] libvisual + libvisual-plugins: Mass-fix typo "[Tt]ransparant" once more
  libvisual-plugins/plugins/actor/dancingparticles/actor_dancingparticles.cpp
  libvisual-plugins/plugins/actor/lv_gltest/actor_lv_gltest.c
  libvisual-plugins/po/de.po
  libvisual-plugins/po/es_AR.po
  libvisual-plugins/po/es_ES.po
  libvisual-plugins/po/libvisual-plugins-0.4.pot
  libvisual/README
Labels: bug

#301 [0.4.x] libvisual: configure.ac: Resolve Bashism
  libvisual/configure.ac
Labels: bug, porting: not needed

#303 Core (LV::Singleton): Fix crash due to differing copies of singleton instances in LV and user programs
  libvisual/libvisual/lv_singleton.hpp
Labels: bug, critical
