Repository Libvisual/libvisual, pull requests merged in 2023-01, with the labels that each got.

#152 [0.4.x] libvisual: Fix splitting of interleaved stereo
  libvisual/libvisual/lv_audio.c
Labels: bug

#159 libvisual-plugins: Fix mplayer input plugin
  libvisual-plugins/plugins/input/mplayer/input_mplayer.c
Labels: bug

#160 libvisual-plugins: Remove ESounD/ESD leftovers
  libvisual-plugins/CMakeLists.txt
  libvisual-plugins/TODO
Labels: enhancement

#151 libvisual: Improve lv-tool a bit
  libvisual/examples/simple/simple_example.cpp
  libvisual/libvisual/lv_cpu.c
  libvisual/tools/lv-tool/display/sdl_driver.cpp
  libvisual/tools/lv-tool/display/stdout_sdl_driver.cpp
  libvisual/tools/lv-tool/lv-tool.cpp
Labels: enhancement

#162 libvisual-plugins: Modernise CMake scripts
  libvisual-plugins/CMakeLists.txt
  libvisual-plugins/cmake/FindLibvisual.cmake
  libvisual-plugins/cmake/LVBuildPlugin.cmake
  libvisual-plugins/common/GL/CMakeLists.txt
  libvisual-plugins/plugins/actor/dancingparticles/CMakeLists.txt
  libvisual-plugins/plugins/actor/gforce/CMakeLists.txt
  libvisual-plugins/plugins/actor/gforce/Common/GeneralTools/CMakeLists.txt
  libvisual-plugins/plugins/actor/gforce/Common/UI/CMakeLists.txt
  libvisual-plugins/plugins/actor/gforce/Common/io/CMakeLists.txt
  libvisual-plugins/plugins/actor/gforce/Common/math/CMakeLists.txt
  libvisual-plugins/plugins/actor/gforce/GForceCommon/CMakeLists.txt
  libvisual-plugins/plugins/actor/gforce/unix/libmfl/CMakeLists.txt
  libvisual-plugins/plugins/actor/gforce/unix/libvisual/CMakeLists.txt
  libvisual-plugins/plugins/actor/goom2k4/CMakeLists.txt
  libvisual-plugins/plugins/actor/madspin/CMakeLists.txt
  libvisual-plugins/plugins/actor/nebulus/CMakeLists.txt
Labels: enhancement

#164 [0.4.x] libvisual-plugins: Free timer during cleanup for actor "lv_gltest"
  libvisual-plugins/plugins/actor/lv_gltest/actor_lv_gltest.c
Labels: bug

#163 libvisual-plugins: Base rotation on runtime not FPS for actor "lv_gltest"
  libvisual-plugins/plugins/actor/lv_gltest/actor_lv_gltest.c
Labels: enhancement

#167 libvisual-plugins: Fix memory leak in lcdcontrol.
  libvisual-plugins/plugins/actor/lcdcontrol/LCDGraphic.cpp
  libvisual-plugins/plugins/actor/lcdcontrol/WidgetVisualization.cpp
Labels: bug

#169 libvisual-plugins: Improve ALSA input plugin
  libvisual-plugins/plugins/input/alsa/CMakeLists.txt
  libvisual-plugins/plugins/input/alsa/input_alsa.c
Labels: enhancement

#174 libvisual: Update Doxygen configuration and fix some errors.
  libvisual/CMakeLists.txt
  libvisual/Doxyfile.in
  libvisual/libvisual/lv_morph.h
  libvisual/libvisual/lv_plugin.h
  libvisual/libvisual/lv_songinfo.h
Labels: bug, documentation

#175 libvisual: Generate and configure Doxygen docs entirely within CMake.
  libvisual/CMakeLists.txt
  libvisual/Doxyfile.in
Labels: documentation

#177 libvisual-plugins: Update actor_pixbuf to build with GTK 3.x
  libvisual-plugins/CMakeLists.txt
Labels: enhancement, bitesized

#178 lv-tool: Upgrade default actor plugin to "lv_gltest" if available
  libvisual/libvisual/lv_actor.cpp
  libvisual/libvisual/lv_actor.h
  libvisual/libvisual/lv_input.cpp
  libvisual/libvisual/lv_input.h
  libvisual/libvisual/lv_morph.cpp
  libvisual/libvisual/lv_morph.h
  libvisual/tools/lv-tool/lv-tool.cpp
Labels: enhancement

#181 lv-tool: Fix broken --actor argument
  libvisual/tools/lv-tool/lv-tool.cpp
Labels: bug

#183 [0.4.x] libvisual-plugins: Update actor_pixbuf to build with GTK 3.x
  .github/workflows/linux.yml
  .github/workflows/translations.yml
  libvisual-plugins/configure.ac
Labels: enhancement

#186 lv-tool: Improve --actor argument
  libvisual/tools/lv-tool/lv-tool.cpp
Labels: enhancement

#187 [0.4.x] libvisual: Fix SDL header location with regard to pkg-config, e.g. for macOS
  libvisual/examples/morphsdl.c
  libvisual/examples/simplesdl.c
  libvisual/tools/lv-tool/Makefile.am
  libvisual/tools/lv-tool/lv-tool.cpp
Labels: bug

#190 lv-tool: Support toggling fullscreen through hotkey F11
  libvisual/tools/lv-tool/display/display.cpp
  libvisual/tools/lv-tool/display/display.hpp
  libvisual/tools/lv-tool/display/display_driver.hpp
  libvisual/tools/lv-tool/display/sdl_driver.cpp
  libvisual/tools/lv-tool/display/stdout_driver.cpp
  libvisual/tools/lv-tool/display/stdout_sdl_driver.cpp
  libvisual/tools/lv-tool/lv-tool.cpp
Labels: enhancement

#188 [0.4.x] libvisual-plugins: configure.ac: Drop unused X11 and make OpenGL logic respect pkg-config (e.g. for macOS)
  libvisual-plugins/configure.ac
  libvisual-plugins/plugins/actor/dancingparticles/Makefile.am
  libvisual-plugins/plugins/actor/lv_gltest/Makefile.am
  libvisual-plugins/plugins/actor/madspin/Makefile.am
  libvisual-plugins/plugins/actor/nastyfft/Makefile.am
  libvisual-plugins/plugins/actor/nebulus/Makefile.am
  libvisual-plugins/plugins/actor/pseudotoad_flower/Makefile.am
Labels: bug

#133 libvisual-plugins: Upgrade to GStreamer 1.x (fixes #95)
  .github/workflows/linux.yml
  .github/workflows/windows.yml
  libvisual-plugins/CMakeLists.txt
  libvisual-plugins/plugins/actor/gstreamer/actor_gstreamer.c
Labels: enhancement

#191 Core, Plugins: Remove LV::clamp() and apply more C++-isms for metaprogramming.
  libvisual-plugins/CMakeLists.txt
  libvisual-plugins/plugins/actor/lcdcontrol/RGBA.h
  libvisual-plugins/plugins/actor/lcdcontrol/SpecialChar.cpp
  libvisual-plugins/plugins/actor/lcdcontrol/SpecialChar.h
  libvisual/libvisual/lv_math.h
  libvisual/libvisual/lv_rectangle.h
  libvisual/libvisual/private/lv_audio_convert.cpp
Labels: enhancement

#194 [0.4.x] libvisual-plugins: Upgrade to GStreamer 1.x (fixes #95)
  .github/workflows/linux_and_macos.yml
  libvisual-plugins/configure.ac
  libvisual-plugins/plugins/actor/gstreamer/actor_gstreamer.c
Labels: enhancement

#192 Core (Docs): Update links and C version requirement in readme files
  libvisual/README
  libvisual/README.md
Labels: bitesized

#199 [0.4.x] libvisual-plugins: Fix out-of-bounds access for actor "lv_flower"
  libvisual-plugins/plugins/actor/pseudotoad_flower/actor_flower.c
Labels: bug

#198 [0.4.x] libvisual-plugins: Make actor "lv_scope" show silence as a solid line
  libvisual-plugins/plugins/actor/lv_scope/actor_lv_scope.c
Labels: enhancement

#197 [0.4.x] Add .gitignore files
  .gitignore
  libvisual/.gitignore
  libvisual/examples/.gitignore
  libvisual/libvisual/.gitignore
  libvisual/tools/lv-tool/.gitignore
Labels: enhancement

#204 libvisual-plugins: Fix out-of-bounds access for actor "lv_flower"
  libvisual-plugins/plugins/actor/flower/actor_flower.c
Labels: bug, porting: done

#202 libvisual-plugins: Fix out-of-bounds access for actor "infinite"
  libvisual-plugins/plugins/actor/infinite/display.c
  libvisual-plugins/plugins/actor/infinite/file.c
  libvisual-plugins/plugins/actor/infinite/renderer.c
  libvisual-plugins/plugins/actor/infinite/renderer.h
Labels: bug, porting: done, porting: TODO

#203 libvisual-plugins: Make actor "lv_scope" show silence as a solid line
  libvisual-plugins/plugins/actor/lv_scope/actor_lv_scope.c
Labels: enhancement, porting: done

#184 [0.4.x] libvisual: Fix ringbuffer infinite loop
  libvisual/libvisual/lv_ringbuffer.c
Labels: bug, critical

#209 [0.4.x] libvisual-plugins: Fix out-of-bounds access for actor "oinksie"
  libvisual-plugins/plugins/actor/oinksie/gfx-background.c
Labels: bug, porting: TODO

#211 libvisual: Fix SDL header location with regard to pkg-config, e.g. for macOS
  libvisual/examples/simple/simple_example.hpp
  libvisual/tools/lv-tool/display/sdl_driver.cpp
  libvisual/tools/lv-tool/display/stdout_sdl_driver.cpp
Labels: enhancement, porting: done

#213 [0.4.x] lv-tool: Fix check for a suitable palette
  libvisual/tools/lv-tool/lv-tool.cpp
Labels: bug, porting: TODO

#217 libvisual-plugins: Fix issues with font loading for actor "gforce"
  libvisual-plugins/plugins/actor/gforce/CMakeLists.txt
  libvisual-plugins/plugins/actor/gforce/Common/UI/CMakeLists.txt
  libvisual-plugins/plugins/actor/gforce/unix/libmfl/mfl.c
Labels: bug, porting: done

#218 Core (LV::IntrusivePtr): Implement swap() overload as a friend function.
  libvisual/libvisual/lv_intrusive_ptr.hpp
Labels: bug, critical

#221 lv-tool: Always skip actors "gstreamer" and "gdkpixbuf" when cycling
  libvisual/tools/lv-tool/lv-tool.cpp
Labels: enhancement, porting: done

#222 [0.4.x] lv-tool: Move constant actors_to_skip next to its siblings
  libvisual/tools/lv-tool/lv-tool.cpp
Labels: enhancement, porting: done

#224 Improve readme
  README.md
Labels: enhancement, porting: not needed

#225 Core, Plugins (Build): Support link options in LV_BUILD_TEST() and LV_BUILD_PLUGIN()
  libvisual-plugins/cmake/LVBuildPlugin.cmake
  libvisual/cmake/LVBuildTest.cmake
Labels: enhancement

#227 [0.4.x] libvisual + libvisual-plugins: Enrich NEWS files with 0.4.1 pull request references
  libvisual-plugins/NEWS
  libvisual/NEWS
Labels: enhancement, documentation, porting: TODO
