Repository Libvisual/libvisual, pull requests merged in 2024-12, with the labels that each got.

#374 [0.4.x] Fix macOS CI / Patch `ax_check_gl.m4` of autoconf-archive 2024.10.16 as needed
  .github/workflows/linux_and_macos.yml
Labels: porting: not needed

#351 [0.4.x] libvisual: fix accidental assignment instead of equality check
  libvisual/libvisual/lv_hashmap.c
Labels: bug, porting: not needed

#244 Core (LV::Video) Fix alpha blending of 32-bit videos (#230)
  libvisual/cmake/LVBuildTest.cmake
  libvisual/libvisual/private/lv_video_blit.cpp
  libvisual/libvisual/private/lv_video_blit_simd.cpp
  libvisual/tests/CMakeLists.txt
  libvisual/tests/random.cpp
  libvisual/tests/random.hpp
  libvisual/tests/video_test/CMakeLists.txt
  libvisual/tests/video_test/video_blit_test.cpp
Labels: bug, critical

#376 [0.4.x] Stop patching `ax_check_gl.m4` for macOS
  .github/workflows/linux_and_macos.yml
Labels: enhancement
