Repository Libvisual/libvisual, pull requests merged in 2025-01, with the labels that each got.

#378 Core (Build): Get ORC compiler executable path from pkg-config.
  libvisual/cmake/FindORC.cmake
Labels: enhancement, porting: not needed

#380 [0.4.x] Stop installing unneeded ORC in CI
  .github/workflows/linux_and_macos.yml
  .github/workflows/translations.yml
Labels: enhancement, porting: not needed

#258 Core (Tests): Add unit test for image loading
  libvisual/tests/images/additive-colors-argb32.png
  libvisual/tests/images/additive-colors-argb32.raw
  libvisual/tests/images/additive-colors-indexed8.bmp
  libvisual/tests/images/additive-colors-indexed8.png
  libvisual/tests/images/additive-colors-indexed8.raw
  libvisual/tests/images/additive-colors-indexed8.raw.pal
  libvisual/tests/images/additive-colors-rgb24.bmp
  libvisual/tests/images/additive-colors-rgb24.png
  libvisual/tests/images/additive-colors-rgb24.raw
  libvisual/tests/images/additive-colors.svg
  libvisual/tests/images/license.txt
  libvisual/tests/video_test/CMakeLists.txt
  libvisual/tests/video_test/video_load_test.cpp
Labels: enhancement, porting: not needed

#382 Plugins (Blursk): Fix double free when Blursk is loaded multiple times.
  libvisual-plugins/plugins/actor/blursk/blursk.c
Labels: bug, critical, porting: not needed

#387 Fix PNG loader not resetting stream position on error right after reading signature
  libvisual/libvisual/private/lv_video_png.cpp
Labels: bug, porting: not needed

#385 Change PNG image loader to load 8-bit indexed images without format conversion
  libvisual/libvisual/private/lv_video_png.cpp
  libvisual/tests/video_test/video_load_test.cpp
Labels: porting: not needed

#384 Add LV::Palette methods for iterations and comparisons
  libvisual/libvisual/lv_palette.h
Labels: enhancement

#383 Plugins (alphablend): Fix blending and associated crashes due to buffer overruns
  libvisual-plugins/plugins/morph/alphablend/morph_alphablend.c
  libvisual/libvisual/lv_alpha_blend.c
  libvisual/libvisual/lv_alpha_blend.h
Labels: bug, critical, porting: TODO

#206 Core (LV::Video): Implement saves to PNG files
  libvisual/CMakeLists.txt
  libvisual/libvisual/CMakeLists.txt
  libvisual/libvisual/lv_video.cpp
  libvisual/libvisual/lv_video.h
  libvisual/libvisual/lv_video_c.cpp
  libvisual/libvisual/private/lv_video_png.cpp
  libvisual/libvisual/private/lv_video_png.hpp
  libvisual/tests/video_test/CMakeLists.txt
  libvisual/tests/video_test/common.cpp
  libvisual/tests/video_test/common.hpp
  libvisual/tests/video_test/video_load_test.cpp
  libvisual/tests/video_test/video_save_test.cpp
Labels: enhancement

#291 Plugins (gforce): Fix GCC warnings
  libvisual-plugins/CMakeLists.txt
  libvisual-plugins/plugins/actor/gforce/CMakeLists.txt
  libvisual-plugins/plugins/actor/gforce/Common/GeneralTools/Headers/XFloatList.h
  libvisual-plugins/plugins/actor/gforce/Common/GeneralTools/XFloatList.cpp
  libvisual-plugins/plugins/actor/gforce/Common/GeneralTools/XStrList.cpp
  libvisual-plugins/plugins/actor/gforce/Common/UI/LineXX.cpp
  libvisual-plugins/plugins/actor/gforce/Common/io/CEgIStream.cpp
  libvisual-plugins/plugins/actor/gforce/Common/math/ExprVirtualMachine.cpp
  libvisual-plugins/plugins/actor/gforce/GForceCommon/GF_Palette.cpp
Labels: porting: TODO, clean up
